"""
scripts/model_presets.py
──────────────────────────────────────────────────────────────────────────────
Shared model preset definitions.

Consumed by:
  • The GitHub Actions workflow (inline Python step)
  • Local training:  python scripts/model_presets.py --model micro --dataset tinystories
  • Any future tooling that imports PRESETS directly

Preset guide (all CPU-trainable on a free GitHub Actions runner):
┌─────────┬───────────┬──────┬────────┬──────┬────────────────────────────┐
│ Preset  │ ~Params   │ dim  │ layers │ seq  │ Target                     │
├─────────┼───────────┼──────┼────────┼──────┼────────────────────────────┤
│ nano    │ ~0.8 M    │  64  │   4    │ 256  │ Wii / MCU (aarossig/ullm)  │
│ micro   │ ~3.5 M    │ 128  │   5    │ 256  │ General embedded / browser │
│ mini    │ ~15 M     │ 288  │   6    │ 256  │ CPU-laptop / richer output │
└─────────┴───────────┴──────┴────────┴──────┴────────────────────────────┘

All models export to the llama2.c v1 float32 LE .bin checkpoint format,
directly loadable by:
  • run.c (karpathy/llama2.c)
  • aarossig/ullm (C, Bazel)
  • ullm.js  (browser / Node, the JS port in this repo)
"""

import argparse, pathlib, os

PRESETS: dict = {
    # ── nano ───────────────────────────────────────────────────────────────
    # Goal: fit into very constrained targets (Wii, ESP32, MCUs).
    # At ~800 K params the whole model is < 4 MB on disk (fp32).
    "nano": dict(
        dim        = 64,
        n_layers   = 4,
        n_heads    = 4,
        n_kv_heads = 4,    # no GQA savings at this size — keep equal
        hidden_dim = 128,
        seq_len    = 256,
        # training
        batch_size   = 32,
        grad_accum   = 1,
        lr           = 8e-4,
        default_iters= 300,
        eval_interval= 100,
        warmup       = 50,
    ),

    # ── micro ──────────────────────────────────────────────────────────────
    # Goal: fast CI runs (~20 min on ubuntu-latest CPU), embedded use.
    # ~3.5 M params, ~14 MB on disk.
    "micro": dict(
        dim        = 128,
        n_layers   = 5,
        n_heads    = 4,
        n_kv_heads = 4,
        hidden_dim = 256,
        seq_len    = 256,
        batch_size   = 32,
        grad_accum   = 2,
        lr           = 5e-4,
        default_iters= 600,
        eval_interval= 200,
        warmup       = 100,
    ),

    # ── mini ───────────────────────────────────────────────────────────────
    # Goal: near-stories15M quality; still tractable on CPU in 6 h.
    # ~15 M params, ~60 MB on disk (same as karpathy's stories15M.bin).
    "mini": dict(
        dim        = 288,
        n_layers   = 6,
        n_heads    = 6,
        n_kv_heads = 6,
        hidden_dim = 768,
        seq_len    = 256,
        batch_size   = 16,
        grad_accum   = 4,
        lr           = 3e-4,
        default_iters= 1000,
        eval_interval= 250,
        warmup       = 100,
    ),
}


def write_train_config(
    model:   str = "micro",
    dataset: str = "tinystories",
    iters:   int = 0,
    resume:  bool = False,
    out_path: str = "llama2.c/train_config.py",
) -> pathlib.Path:
    """
    Renders a train_config.py for llama2.c/train.py and writes it to out_path.
    Returns the path written.
    """
    if model not in PRESETS:
        raise ValueError(f"Unknown model preset '{model}'. Choose from: {list(PRESETS)}")

    p         = PRESETS[model]
    max_iters = iters if iters > 0 else p["default_iters"]
    data_dir  = "data" if dataset == "tinystories" else f"data/{dataset}"

    cfg = f"""\
# Auto-generated by scripts/model_presets.py
# Model preset : {model}   (~{_approx_params(p):,} params)
# Dataset      : {dataset}
# Max iters    : {max_iters}

# ── Model Architecture ──────────────────────────────────────────────────────
dim            = {p["dim"]}
n_layers       = {p["n_layers"]}
n_heads        = {p["n_heads"]}
n_kv_heads     = {p["n_kv_heads"]}
multiple_of    = 32
max_seq_len    = {p["seq_len"]}

# ── Training ────────────────────────────────────────────────────────────────
max_iters                   = {max_iters}
batch_size                  = {p["batch_size"]}
gradient_accumulation_steps = {p["grad_accum"]}
learning_rate               = {p["lr"]}
warmup_iters                = {p["warmup"]}
lr_decay_iters              = {max_iters}
min_lr                      = {p["lr"] * 0.1}
weight_decay                = 0.1
grad_clip                   = 1.0
beta1                       = 0.9
beta2                       = 0.95

# ── Logging / Evaluation ────────────────────────────────────────────────────
eval_interval           = {p["eval_interval"]}
log_interval            = 10
eval_iters              = 20
eval_only               = False
always_save_checkpoint  = True

# ── I/O ─────────────────────────────────────────────────────────────────────
out_dir    = "out"
init_from  = "{'resume' if resume else 'scratch'}"

# ── Data ────────────────────────────────────────────────────────────────────
dataset      = "{data_dir}"
vocab_source = "llama2"
vocab_size   = 32000

# ── Hardware ────────────────────────────────────────────────────────────────
device  = "cpu"
dtype   = "float32"
compile = False
"""

    out = pathlib.Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(cfg)
    return out


def _approx_params(p: dict) -> int:
    """Very rough parameter count estimate."""
    d, h, l, ff = p["dim"], p["n_heads"], p["n_layers"], p["hidden_dim"]
    attn = 4 * d * d
    ffn  = 3 * d * ff
    return int((attn + ffn) * l + 32000 * d)


# ── CLI ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Write a train_config.py for llama2.c")
    ap.add_argument("--model",   default="micro",
                    choices=list(PRESETS), help="Model size preset")
    ap.add_argument("--dataset", default="tinystories",
                    help="Dataset name (tinystories | explain_code | …)")
    ap.add_argument("--iters",   type=int, default=0,
                    help="Override max_iters (0 = use preset default)")
    ap.add_argument("--resume",  action="store_true",
                    help="Set init_from=resume instead of scratch")
    ap.add_argument("--out",     default="llama2.c/train_config.py",
                    help="Output path for the generated config")
    args = ap.parse_args()

    path = write_train_config(
        model=args.model, dataset=args.dataset,
        iters=args.iters, resume=args.resume, out_path=args.out)

    print(f"Config written → {path}")
    print(open(path).read())
